language: node_js
# cache:
#   directories:
#   - node_modules
node_js:
    - "10"
    - "8"
before_script:
  - npm run setup
script:
  - npm test

notifications:
  email:
    on_success: never
    on_failure: always