language: node_js
node_js:
  - 10
  - 11
  - 12
services:
  - redis-server
before_script:
  # install NATS server
  - wget https://github.com/nats-io/nats-server/releases/download/v2.0.0/nats-server-v2.0.0-linux-amd64.zip -qO nats-server.zip
  - unzip nats-server.zip
  - ./nats-server-v2.0.0-linux-amd64/nats-server &

script:
  - npm ci
  - npm test
notifications:
  email: false
  slack: fachwerk:de3wPX9uXaZW21xoewXG28gf