version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    default_assignees:
    - "kevinries"
    default_labels:
    - "Dependencies"
    commit_message:
      prefix: "fix"
      prefix_development: "chore"
    allowed_updates:
    - match:
        dependency_type: "direct"
        update_type: "all"
    version_requirement_updates: "increase_versions"

  - package_manager: "javascript"
    directory: "/packages/cli"
    update_schedule: "live"
    default_assignees:
    - "kevinries"
    default_labels:
    - "Dependencies"
    commit_message:
      prefix: "fix"
      prefix_development: "chore"
    allowed_updates:
    - match:
        dependency_type: "direct"
        update_type: "all"
    version_requirement_updates: "increase_versions"

  - package_manager: "javascript"
    directory: "/packages/core"
    update_schedule: "live"
    default_assignees:
    - "kevinries"
    default_labels:
    - "Dependencies"
    commit_message:
      prefix: "fix"
      prefix_development: "chore"
    allowed_updates:
    - match:
        dependency_type: "direct"
        update_type: "all"
    version_requirement_updates: "increase_versions"

  - package_manager: "javascript"
    directory: "/packages/repl"
    update_schedule: "live"
    default_assignees:
    - "kevinries"
    default_labels:
    - "Dependencies"
    commit_message:
      prefix: "fix"
      prefix_development: "chore"
    allowed_updates:
    - match:
        dependency_type: "direct"
        update_type: "all"
    version_requirement_updates: "increase_versions"

  - package_manager: "javascript"
    directory: "/packages/utils"
    update_schedule: "live"
    default_assignees:
    - "kevinries"
    default_labels:
    - "Dependencies"
    commit_message:
      prefix: "fix"
      prefix_development: "chore"
    allowed_updates:
    - match:
        dependency_type: "direct"
        update_type: "all"
    version_requirement_updates: "increase_versions"

  - package_manager: "javascript"
    directory: "/packages/validator"
    update_schedule: "live"
    default_assignees:
    - "kevinries"
    default_labels:
    - "Dependencies"
    commit_message:
      prefix: "fix"
      prefix_development: "chore"
    allowed_updates:
    - match:
        dependency_type: "direct"
        update_type: "all"
    version_requirement_updates: "increase_versions"